version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "17:00"
    timezone: Japan
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nock
    versions:
    - 13.0.10
    - 13.0.11
    - 13.0.6
    - 13.0.7
    - 13.0.8
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: ethereumjs-util
    versions:
    - 7.0.7
    - 7.0.8
    - 7.0.9
  - dependency-name: jayson
    versions:
    - 3.4.4
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 3.9.1
