name: E2E Test

on:
  pull_request_target:
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  test-e2e:
    needs: [setup]
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') || (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]')

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
      if: (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]')
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - uses: actions/checkout@v2
      if: (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]')
      with:
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: cache node_modules
      id: node_modules_cache_id
      uses: actions/cache@v2
      with:
        path: |
          node_modules
        key: node-v${{ matrix.node-version }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
    - name: Geth Action
      id: geth
      uses: odanado/geth-action@v0.0.10

    - name: run e2e test
      run: |
        yarn e2e
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        RPC_URL: ${{ steps.geth.outputs.rpc_url }}
        PRIVATE_KEY: ${{ steps.geth.outputs.private_key }}
